version: '3.8'

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - network

  php-fpm:
    build: 
      context: .
      dockerfile: Dockerfile.php-fpm
    container_name: php-fpm
    volumes:
      - .:/var/www/html
    networks:
      - network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1q2w3e4r'
      MYSQL_DATABASE: 'web-app'
      MYSQL_USER: 'ironman'
      MYSQL_PASSWORD: '1q2w3e4r'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8090:80"
    depends_on:
      - mysql
    networks:
      - network

  redis-server:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - network

volumes:
  mysql_data:

networks:
  network:
    driver: bridge